# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build and push images 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag reverseproxy hnass/reverseproxy:v1
    - run: docker tag udagram-api-user hnass/udagram-api-user:v1
    - run: docker tag udagram-api-feed hnass/udagram-api-feed:v1
    - run: docker tag reverseproxy hnass/reverseproxy:v1
    - run: docker tag udagram-frontend:local hnass/udagram-frontend:v1
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push  hnass/reverseproxy:v1
    - run: docker push  hnass/udagram-api-user:v1
    - run: docker push  hnass/udagram-api-feed:v1
    - run: docker push  hnass/reverseproxy:v1
    - run: docker push  hnass/udagram-frontend:v1
